'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import type { NotificationEvent } from '@shepai/core/domain/generated/output';
import type {
  AgentMessageStreamEvent,
  AgentQuestionStreamEvent,
  SupervisorDecisionStreamEvent,
} from '@shepai/core/application/use-cases/agents/stream-agent-events.use-case';
import { createLogger } from '@/lib/logger';
import { AGENT_EVENTS_HEARTBEAT_EVENT, appendBounded, upsertById } from '@/lib/agent-event-stream';

export type ConnectionStatus = 'connected' | 'connecting' | 'disconnected';

export interface UseAgentEventsOptions {
  runId?: string;
}

/**
 * Spec 093 — collaboration event union surfaced alongside the legacy
 * notification stream. Each member is a discriminated stream-event envelope
 * generated by the SSE pipeline; presentation consumers narrow on `kind`.
 */
export type CollaborationStreamEvent =
  | AgentMessageStreamEvent
  | AgentQuestionStreamEvent
  | SupervisorDecisionStreamEvent;

export interface UseAgentEventsResult {
  events: NotificationEvent[];
  lastEvent: NotificationEvent | null;

  /** Spec 093 — agent message bus events for the per-feature activity feed. */
  agentMessages: AgentMessageStreamEvent[];
  lastAgentMessage: AgentMessageStreamEvent | null;
  /** Spec 093 — unified agent-question pipeline events for the inbox. */
  agentQuestions: AgentQuestionStreamEvent[];
  lastAgentQuestion: AgentQuestionStreamEvent | null;
  /** Spec 093 — supervisor decision events for the "Why?" drawer. */
  supervisorDecisions: SupervisorDecisionStreamEvent[];
  lastSupervisorDecision: SupervisorDecisionStreamEvent | null;

  connectionStatus: ConnectionStatus;
}

const log = createLogger('[SSE]');
const SW_PATH = '/agent-events-sw.js';

/** Stream channels carrying a payload; the SW relays each one as `{ type, data }`. */
const DATA_CHANNELS = [
  'notification',
  'agent_message',
  'agent_question',
  'supervisor_decision',
] as const;
type DataChannel = (typeof DATA_CHANNELS)[number];

const messageKey = (m: AgentMessageStreamEvent) => m.messageId;
const questionKey = (q: AgentQuestionStreamEvent) => q.questionId;
const decisionKey = (d: SupervisorDecisionStreamEvent) => d.decisionId;

/**
 * Apply one stream payload to the hook state. Collaboration rows are keyed by
 * id so a row delivered twice (e.g. replayed on reconnect) is kept once and a
 * later delivery of the same id (a question status change) replaces it.
 */
function applyStreamPayload(
  channel: DataChannel,
  data: unknown,
  setters: DirectFallbackSetters
): void {
  switch (channel) {
    case 'notification': {
      const parsed = data as NotificationEvent;
      log.debug('event received:', parsed.eventType, parsed);
      setters.setEvents((prev) => appendBounded(prev, parsed));
      setters.setLastEvent(parsed);
      return;
    }
    case 'agent_message': {
      const parsed = data as AgentMessageStreamEvent;
      setters.setAgentMessages((prev) => upsertById(prev, parsed, messageKey));
      setters.setLastAgentMessage(parsed);
      return;
    }
    case 'agent_question': {
      const parsed = data as AgentQuestionStreamEvent;
      setters.setAgentQuestions((prev) => upsertById(prev, parsed, questionKey));
      setters.setLastAgentQuestion(parsed);
      return;
    }
    case 'supervisor_decision': {
      const parsed = data as SupervisorDecisionStreamEvent;
      setters.setSupervisorDecisions((prev) => upsertById(prev, parsed, decisionKey));
      setters.setLastSupervisorDecision(parsed);
      return;
    }
  }
}

function isDataChannel(type: unknown): type is DataChannel {
  return (DATA_CHANNELS as readonly unknown[]).includes(type);
}

/**
 * Hook that receives real-time agent notification events via a Service Worker.
 *
 * The SW maintains a single SSE connection to /api/agent-events and
 * broadcasts events to all open tabs. Falls back to direct EventSource
 * when Service Workers are unavailable.
 */
export function useAgentEvents(options?: UseAgentEventsOptions): UseAgentEventsResult {
  const [events, setEvents] = useState<NotificationEvent[]>([]);
  const [lastEvent, setLastEvent] = useState<NotificationEvent | null>(null);

  const [agentMessages, setAgentMessages] = useState<AgentMessageStreamEvent[]>([]);
  const [lastAgentMessage, setLastAgentMessage] = useState<AgentMessageStreamEvent | null>(null);

  const [agentQuestions, setAgentQuestions] = useState<AgentQuestionStreamEvent[]>([]);
  const [lastAgentQuestion, setLastAgentQuestion] = useState<AgentQuestionStreamEvent | null>(null);

  const [supervisorDecisions, setSupervisorDecisions] = useState<SupervisorDecisionStreamEvent[]>(
    []
  );
  const [lastSupervisorDecision, setLastSupervisorDecision] =
    useState<SupervisorDecisionStreamEvent | null>(null);

  const [connectionStatus, setConnectionStatus] = useState<ConnectionStatus>('disconnected');

  const runId = options?.runId;
  const swRef = useRef<ServiceWorker | null>(null);

  const onMessage = useCallback((event: MessageEvent) => {
    const msg = event.data;
    if (!msg || typeof msg !== 'object') return;

    if (isDataChannel(msg.type)) {
      applyStreamPayload(msg.type, msg.data, {
        setEvents,
        setLastEvent,
        setAgentMessages,
        setLastAgentMessage,
        setAgentQuestions,
        setLastAgentQuestion,
        setSupervisorDecisions,
        setLastSupervisorDecision,
        setConnectionStatus,
      });
    } else if (msg.type === 'status') {
      setConnectionStatus(msg.status as ConnectionStatus);
    }
  }, []);

  useEffect(() => {
    if (typeof window === 'undefined') return;

    // ?sse=direct bypasses the Service Worker for debugging
    const bypassSW =
      typeof location !== 'undefined' && new URLSearchParams(location.search).has('sse');

    // Fallback: direct EventSource when SW not supported or bypassed
    if (!navigator.serviceWorker || bypassSW) {
      return connectDirectEventSource(runId, {
        setEvents,
        setLastEvent,
        setAgentMessages,
        setLastAgentMessage,
        setAgentQuestions,
        setLastAgentQuestion,
        setSupervisorDecisions,
        setLastSupervisorDecision,
        setConnectionStatus,
      });
    }

    let cancelled = false;
    const fallbackCleanupRef = { current: undefined as (() => void) | undefined };

    function subscribeToWorker(worker: ServiceWorker) {
      if (cancelled) return;
      swRef.current = worker;
      worker.postMessage({ type: 'subscribe', runId });
      setConnectionStatus('connecting');
    }

    // Listen for messages from whatever SW controls this page
    navigator.serviceWorker.addEventListener('message', onMessage);

    // Re-subscribe when SW controller changes (e.g., after SW update via skipWaiting)
    function handleControllerChange() {
      if (cancelled) return;
      const newController = navigator.serviceWorker.controller;
      if (newController) {
        swRef.current = newController;
        newController.postMessage({ type: 'subscribe', runId });
        setConnectionStatus('connecting');
      }
    }
    navigator.serviceWorker.addEventListener('controllerchange', handleControllerChange);

    navigator.serviceWorker
      .register(SW_PATH, { scope: '/' })
      .then((registration) => {
        if (cancelled) return;

        // Use the active worker, or wait for it to activate
        const sw = registration.active ?? registration.installing ?? registration.waiting;
        if (!sw) {
          // No worker at all — fall back to direct EventSource
          fallbackCleanupRef.current = connectDirectEventSource(runId, {
            setEvents,
            setLastEvent,
            setAgentMessages,
            setLastAgentMessage,
            setAgentQuestions,
            setLastAgentQuestion,
            setSupervisorDecisions,
            setLastSupervisorDecision,
            setConnectionStatus,
          });
          return;
        }

        if (sw.state === 'activated') {
          subscribeToWorker(sw);
        } else {
          const onStateChange = () => {
            if (sw.state === 'activated') {
              sw.removeEventListener('statechange', onStateChange);
              subscribeToWorker(sw);
            }
          };
          sw.addEventListener('statechange', onStateChange);
        }
      })
      .catch(() => {
        // SW registration failed — fall back to direct EventSource
        if (!cancelled) {
          fallbackCleanupRef.current = connectDirectEventSource(runId, {
            setEvents,
            setLastEvent,
            setAgentMessages,
            setLastAgentMessage,
            setAgentQuestions,
            setLastAgentQuestion,
            setSupervisorDecisions,
            setLastSupervisorDecision,
            setConnectionStatus,
          });
        }
      });

    return () => {
      cancelled = true;
      navigator.serviceWorker.removeEventListener('message', onMessage);
      navigator.serviceWorker.removeEventListener('controllerchange', handleControllerChange);
      swRef.current?.postMessage({ type: 'unsubscribe' });
      swRef.current = null;
      fallbackCleanupRef.current?.();
    };
  }, [runId, onMessage]);

  return {
    events,
    lastEvent,
    agentMessages,
    lastAgentMessage,
    agentQuestions,
    lastAgentQuestion,
    supervisorDecisions,
    lastSupervisorDecision,
    connectionStatus,
  };
}

// --- EventSource fallback (identical to the previous implementation) ---

const BASE_BACKOFF_MS = 1000;
const MAX_BACKOFF_MS = 30_000;
const STABLE_CONNECTION_MS = 5_000;
const HEARTBEAT_TIMEOUT_MS = 60_000; // Close connection if no message for 60s

interface DirectFallbackSetters {
  setEvents: React.Dispatch<React.SetStateAction<NotificationEvent[]>>;
  setLastEvent: React.Dispatch<React.SetStateAction<NotificationEvent | null>>;
  setAgentMessages: React.Dispatch<React.SetStateAction<AgentMessageStreamEvent[]>>;
  setLastAgentMessage: React.Dispatch<React.SetStateAction<AgentMessageStreamEvent | null>>;
  setAgentQuestions: React.Dispatch<React.SetStateAction<AgentQuestionStreamEvent[]>>;
  setLastAgentQuestion: React.Dispatch<React.SetStateAction<AgentQuestionStreamEvent | null>>;
  setSupervisorDecisions: React.Dispatch<React.SetStateAction<SupervisorDecisionStreamEvent[]>>;
  setLastSupervisorDecision: React.Dispatch<
    React.SetStateAction<SupervisorDecisionStreamEvent | null>
  >;
  setConnectionStatus: React.Dispatch<React.SetStateAction<ConnectionStatus>>;
}

function connectDirectEventSource(
  runId: string | undefined,
  setters: DirectFallbackSetters
): () => void {
  // eslint-disable-next-line @typescript-eslint/no-empty-function
  if (typeof EventSource === 'undefined') return () => {};

  let es: EventSource | null = null;
  let stopped = false;
  let backoff = BASE_BACKOFF_MS;
  let reconnectTimer: ReturnType<typeof setTimeout> | null = null;
  let stableTimer: ReturnType<typeof setTimeout> | null = null;
  let heartbeatTimer: ReturnType<typeof setTimeout> | null = null;

  const resetHeartbeatTimeout = (): void => {
    if (heartbeatTimer !== null) {
      clearTimeout(heartbeatTimer);
    }
    if (stopped || !es) return;
    heartbeatTimer = setTimeout(() => {
      heartbeatTimer = null;
      log.warn('No heartbeat received within timeout, reconnecting...');
      es?.close();
      es = null;
      setters.setConnectionStatus('disconnected');
      if (stableTimer !== null) {
        clearTimeout(stableTimer);
        stableTimer = null;
      }
      const delay = backoff;
      backoff = Math.min(delay * 2, MAX_BACKOFF_MS);
      reconnectTimer = setTimeout(() => {
        reconnectTimer = null;
        connect();
      }, delay);
    }, HEARTBEAT_TIMEOUT_MS);
  };

  function connect() {
    if (stopped) return;

    const url = runId
      ? `/api/agent-events?runId=${encodeURIComponent(runId)}`
      : '/api/agent-events';

    es = new EventSource(url);
    setters.setConnectionStatus('connecting');

    es.onopen = () => {
      setters.setConnectionStatus('connected');
      resetHeartbeatTimeout();
      stableTimer = setTimeout(() => {
        stableTimer = null;
        backoff = BASE_BACKOFF_MS;
      }, STABLE_CONNECTION_MS);
    };

    es.onerror = () => {
      es?.close();
      es = null;
      setters.setConnectionStatus('disconnected');

      if (stableTimer !== null) {
        clearTimeout(stableTimer);
        stableTimer = null;
      }

      if (heartbeatTimer !== null) {
        clearTimeout(heartbeatTimer);
        heartbeatTimer = null;
      }

      const delay = backoff;
      backoff = Math.min(delay * 2, MAX_BACKOFF_MS);

      reconnectTimer = setTimeout(() => {
        reconnectTimer = null;
        connect();
      }, delay);
    };

    for (const channel of DATA_CHANNELS) {
      es.addEventListener(channel, ((event: MessageEvent) => {
        resetHeartbeatTimeout();
        applyStreamPayload(channel, JSON.parse(event.data), setters);
      }) as EventListener);
    }

    // The server's keep-alive: carries no payload, only proves the stream is live.
    es.addEventListener(AGENT_EVENTS_HEARTBEAT_EVENT, resetHeartbeatTimeout);
  }

  connect();

  return () => {
    stopped = true;
    if (reconnectTimer !== null) {
      clearTimeout(reconnectTimer);
      reconnectTimer = null;
    }
    if (stableTimer !== null) {
      clearTimeout(stableTimer);
      stableTimer = null;
    }
    if (heartbeatTimer !== null) {
      clearTimeout(heartbeatTimer);
      heartbeatTimer = null;
    }
    if (es) {
      es.close();
      es = null;
    }
  };
}
