#!/usr/bin/env node
/**
 * gen-config.mjs — single source of truth → pm2 + reverse-proxy configs.
 *
 * Reads deploy/tenants.json and generates:
 *   - deploy/ecosystem.config.cjs        (pm2: one process per tenant, isolated by env)
 *   - one of:
 *       deploy/shep.nginx.conf  + deploy/htpasswd/<id>   (proxy: "nginx", default)
 *       deploy/Caddyfile                                 (proxy: "caddy")
 *
 * Per-tenant isolation (no app code change needed):
 *   SHEP_HOME       → its own DB, secrets, worktrees, projects, logs, checkpoints
 *   GH_CONFIG_DIR   → its own GitHub credentials (gh CLI honors this natively)
 *   SHEP_BIND_HOST  → 127.0.0.1 so the app is never directly public
 *   --port <N>      → its own listen port behind the reverse proxy
 *
 * Claude auth: NOT handled here. The agents spawn the `claude` CLI, which uses
 * its own login (~/.claude) — shared by all tenants as long as pm2 runs as the
 * same OS user that ran `claude login`. Optionally set CLAUDE_CODE_OAUTH_TOKEN /
 * ANTHROPIC_API_KEY in the pm2 environment and it will be inherited.
 *
 * Usage:  node deploy/gen-config.mjs [path/to/tenants.json]
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const configPath = resolve(process.argv[2] ?? join(here, 'tenants.json'));

const CLAUDE_TOKEN_ENV = 'CLAUDE_CODE_OAUTH_TOKEN';
/** Routes that must stay reachable WITHOUT login (they self-verify HMAC signatures). */
const WEBHOOK_PREFIX = '/api/webhooks/';
const WHATSAPP_WEBHOOK = '/api/whatsapp/webhook';

function loadConfig() {
  let raw;
  try {
    raw = readFileSync(configPath, 'utf8');
  } catch (err) {
    fail(`Cannot read ${configPath}: ${err.message}`);
  }
  let cfg;
  try {
    cfg = JSON.parse(raw);
  } catch (err) {
    fail(`Invalid JSON in ${configPath}: ${err.message}`);
  }
  cfg.proxy = cfg.proxy ?? 'nginx';
  validate(cfg);
  return cfg;
}

function validate(cfg) {
  for (const key of ['domain', 'appDir', 'tenantsRoot', 'appEntry', 'tenants']) {
    if (!cfg[key]) fail(`tenants.json is missing required key: "${key}"`);
  }
  if (!['nginx', 'caddy'].includes(cfg.proxy)) {
    fail(`tenants.json "proxy" must be "nginx" or "caddy" (got "${cfg.proxy}")`);
  }
  if (cfg.proxy === 'nginx') {
    if (!cfg.tls?.cert || !cfg.tls?.key) {
      fail('nginx mode requires "tls": { "cert": "...", "key": "..." } (your wildcard cert)');
    }
    if (!cfg.htpasswdDir) fail('nginx mode requires "htpasswdDir" (e.g. /etc/nginx/shep)');
  }
  if (!Array.isArray(cfg.tenants) || cfg.tenants.length === 0) {
    fail('tenants.json "tenants" must be a non-empty array');
  }
  const seen = { id: new Set(), subdomain: new Set(), port: new Set() };
  for (const t of cfg.tenants) {
    for (const key of ['id', 'subdomain', 'port']) {
      if (t[key] === undefined || t[key] === null || t[key] === '') {
        fail(`tenant ${JSON.stringify(t)} is missing "${key}"`);
      }
      if (seen[key].has(t[key])) fail(`duplicate ${key}: ${t[key]}`);
      seen[key].add(t[key]);
    }
    if (!t.authHash || String(t.authHash).startsWith('REPLACE_')) {
      warn(`tenant "${t.id}" has no real authHash — its login will fail until set.`);
    }
  }
}

const shepHome = (cfg, t) => join(cfg.tenantsRoot, t.id, '.shep');
const ghConfigDir = (cfg, t) => join(cfg.tenantsRoot, t.id, 'gh');
const host = (cfg, t) => `${t.subdomain}.${cfg.domain}`;
const upstream = (cfg, t) => `${cfg.bindHost ?? '127.0.0.1'}:${t.port}`;

// ── pm2 ──────────────────────────────────────────────────────────────────────
function renderEcosystem(cfg) {
  const appBlocks = cfg.tenants
    .map((t) => {
      const env = [
        `        NODE_ENV: "production",`,
        `        SHEP_BIND_HOST: ${JSON.stringify(cfg.bindHost ?? '127.0.0.1')},`,
        `        SHEP_HOME: ${JSON.stringify(shepHome(cfg, t))},`,
        `        GH_CONFIG_DIR: ${JSON.stringify(ghConfigDir(cfg, t))},`,
        // Inherited from the pm2 parent env if present; harmless (undefined) if not.
        `        ${CLAUDE_TOKEN_ENV}: process.env.${CLAUDE_TOKEN_ENV},`,
      ].join('\n');
      return `    {
      name: ${JSON.stringify(`shep-${t.id}`)},
      script: ${JSON.stringify(join(cfg.appDir, cfg.appEntry))},
      args: ${JSON.stringify(`_serve --port ${t.port}`)},
      interpreter: "node",
      cwd: ${JSON.stringify(cfg.appDir)},
      autorestart: true,
      max_restarts: 10,
      watch: false,
      max_memory_restart: "1500M",
      env: {
${env}
      },
    }`;
    })
    .join(',\n');

  return `// AUTO-GENERATED by deploy/gen-config.mjs from deploy/tenants.json — DO NOT EDIT.
// Regenerate with: node deploy/gen-config.mjs
module.exports = {
  apps: [
${appBlocks}
  ],
};
`;
}

// ── nginx ────────────────────────────────────────────────────────────────────
function proxyHeaders(cfg, t) {
  return [
    `        proxy_pass http://${upstream(cfg, t)};`,
    `        proxy_http_version 1.1;`,
    `        proxy_set_header Upgrade $http_upgrade;`,
    `        proxy_set_header Connection $connection_upgrade;`,
    `        proxy_set_header Host $host;`,
    `        proxy_set_header X-Real-IP $remote_addr;`,
    `        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`,
    `        proxy_set_header X-Forwarded-Proto $scheme;`,
    `        proxy_buffering off;        # required for SSE / streaming agent output`,
    `        proxy_read_timeout 3600s;`,
    `        client_max_body_size 100m;`,
  ].join('\n');
}

function renderNginx(cfg) {
  const blocks = cfg.tenants
    .map((t) => {
      const h = host(cfg, t);
      const htpasswd = join(cfg.htpasswdDir, `${t.id}.htpasswd`);
      return `# ${t.id}
server {
    listen 80;
    server_name ${h};
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    http2 on;
    server_name ${h};

    ssl_certificate     ${cfg.tls.cert};
    ssl_certificate_key ${cfg.tls.key};

    # Webhooks self-verify HMAC signatures — no login required.
    location ^~ ${WEBHOOK_PREFIX} {
${proxyHeaders(cfg, t)}
    }
    location = ${WHATSAPP_WEBHOOK} {
${proxyHeaders(cfg, t)}
    }

    # Everything else requires a login (identity-based — survives IP changes).
    location / {
        auth_basic "${h}";
        auth_basic_user_file ${htpasswd};
${proxyHeaders(cfg, t)}
    }
}`;
    })
    .join('\n\n');

  return `# AUTO-GENERATED by deploy/gen-config.mjs from deploy/tenants.json — DO NOT EDIT.
# Regenerate with: node deploy/gen-config.mjs
# Install: sudo cp deploy/shep.nginx.conf /etc/nginx/conf.d/shep.conf && sudo nginx -t && sudo systemctl reload nginx

# Needed once (http context) for WebSocket/SSE upgrades:
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

${blocks}
`;
}

function writeHtpasswdFiles(cfg) {
  const dir = join(here, 'htpasswd');
  mkdirSync(dir, { recursive: true });
  for (const t of cfg.tenants) {
    const user = t.authUser ?? t.id;
    writeFileSync(join(dir, `${t.id}.htpasswd`), `${user}:${t.authHash}\n`);
  }
  return dir;
}

// ── caddy (alternative) ───────────────────────────────────────────────────────
function renderCaddyfile(cfg) {
  const blocks = cfg.tenants.map((t) => {
    const user = t.authUser ?? t.id;
    return `${host(cfg, t)} {
\t@webhooks path ${WEBHOOK_PREFIX}* ${WHATSAPP_WEBHOOK}
\thandle @webhooks {
\t\treverse_proxy ${upstream(cfg, t)}
\t}
\thandle {
\t\tbasic_auth {
\t\t\t${user} ${t.authHash}
\t\t}
\t\treverse_proxy ${upstream(cfg, t)}
\t}
}`;
  });
  return `# AUTO-GENERATED by deploy/gen-config.mjs — DO NOT EDIT.\n\n${blocks.join('\n\n')}\n`;
}

// ── helpers ───────────────────────────────────────────────────────────────────
function fail(msg) {
  console.error(`\x1b[31m✖ ${msg}\x1b[0m`);
  process.exit(1);
}
function warn(msg) {
  console.warn(`\x1b[33m⚠ ${msg}\x1b[0m`);
}
function ok(msg) {
  console.log(`\x1b[32m✓ ${msg}\x1b[0m`);
}

// ── run ───────────────────────────────────────────────────────────────────────
const cfg = loadConfig();
const ecosystemPath = join(here, 'ecosystem.config.cjs');
writeFileSync(ecosystemPath, renderEcosystem(cfg));
ok(`Wrote ${ecosystemPath}`);

if (cfg.proxy === 'nginx') {
  const confPath = join(here, 'shep.nginx.conf');
  writeFileSync(confPath, renderNginx(cfg));
  const hdir = writeHtpasswdFiles(cfg);
  ok(`Wrote ${confPath}`);
  ok(`Wrote htpasswd files in ${hdir}/`);
} else {
  const caddyPath = join(here, 'Caddyfile');
  writeFileSync(caddyPath, renderCaddyfile(cfg));
  ok(`Wrote ${caddyPath}`);
}

console.log(`\nTenants (${cfg.tenants.length}):`);
for (const t of cfg.tenants) {
  console.log(
    `  • ${String(t.id).padEnd(12)} https://${host(cfg, t)}  →  ${upstream(cfg, t)}  (SHEP_HOME=${shepHome(cfg, t)})`
  );
}
