#!/usr/bin/env node
/**
 * gen-config.mjs — single source of truth → pm2 + Caddy configs.
 *
 * Reads deploy/tenants.json and generates:
 *   - deploy/ecosystem.config.cjs   (pm2: one process per tenant, isolated by env)
 *   - deploy/Caddyfile              (per-subdomain login gate → 127.0.0.1:<port>)
 *
 * Each tenant is fully isolated via env vars (no app code change needed):
 *   SHEP_HOME       → its own DB, secrets, worktrees, projects, logs, checkpoints
 *   GH_CONFIG_DIR   → its own GitHub credentials (gh CLI honors this natively)
 *   SHEP_BIND_HOST  → 127.0.0.1 so the app is never directly public
 *   --port <N>      → its own listen port behind the reverse proxy
 *
 * The Claude key is shared across all tenants and is NOT written here — it is
 * read from the ambient environment (CLAUDE_CODE_OAUTH_TOKEN) by pm2 at start,
 * keeping the secret out of generated files and source control.
 *
 * Usage:  node deploy/gen-config.mjs [path/to/tenants.json]
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const configPath = resolve(process.argv[2] ?? join(here, 'tenants.json'));

/** Shared env var name for the Claude Code subscription/OAuth token. */
const CLAUDE_TOKEN_ENV = 'CLAUDE_CODE_OAUTH_TOKEN';
/** Routes that must stay reachable WITHOUT login (they self-verify HMAC signatures). */
const WEBHOOK_PATHS = ['/api/webhooks/*', '/api/whatsapp/webhook'];

function loadConfig() {
  let raw;
  try {
    raw = readFileSync(configPath, 'utf8');
  } catch (err) {
    fail(`Cannot read ${configPath}: ${err.message}`);
  }
  let cfg;
  try {
    cfg = JSON.parse(raw);
  } catch (err) {
    fail(`Invalid JSON in ${configPath}: ${err.message}`);
  }
  validate(cfg);
  return cfg;
}

function validate(cfg) {
  const required = ['domain', 'appDir', 'tenantsRoot', 'appEntry', 'tenants'];
  for (const key of required) {
    if (!cfg[key]) fail(`tenants.json is missing required key: "${key}"`);
  }
  if (!Array.isArray(cfg.tenants) || cfg.tenants.length === 0) {
    fail('tenants.json "tenants" must be a non-empty array');
  }
  const seenPorts = new Set();
  const seenIds = new Set();
  const seenSubs = new Set();
  for (const t of cfg.tenants) {
    for (const key of ['id', 'subdomain', 'port']) {
      if (t[key] === undefined || t[key] === null || t[key] === '') {
        fail(`tenant ${JSON.stringify(t)} is missing "${key}"`);
      }
    }
    if (seenIds.has(t.id)) fail(`duplicate tenant id: ${t.id}`);
    if (seenSubs.has(t.subdomain)) fail(`duplicate subdomain: ${t.subdomain}`);
    if (seenPorts.has(t.port)) fail(`duplicate port: ${t.port}`);
    seenIds.add(t.id);
    seenSubs.add(t.subdomain);
    seenPorts.add(t.port);
    if (!t.authHash || t.authHash.startsWith('REPLACE_')) {
      warn(`tenant "${t.id}" has no real authHash — its subdomain will reject logins until set.`);
    }
  }
}

function shepHome(cfg, t) {
  return join(cfg.tenantsRoot, t.id, '.shep');
}
function ghConfigDir(cfg, t) {
  return join(cfg.tenantsRoot, t.id, 'gh');
}

function renderEcosystem(cfg) {
  const apps = cfg.tenants.map((t) => ({
    name: `shep-${t.id}`,
    script: join(cfg.appDir, cfg.appEntry),
    args: `_serve --port ${t.port}`,
    interpreter: 'node',
    cwd: cfg.appDir,
    autorestart: true,
    max_restarts: 10,
    watch: false,
    max_memory_restart: '1500M',
    env: {
      NODE_ENV: 'production',
      SHEP_BIND_HOST: cfg.bindHost ?? '127.0.0.1',
      SHEP_HOME: shepHome(cfg, t),
      GH_CONFIG_DIR: ghConfigDir(cfg, t),
      // Shared Claude token: inherited from the pm2 parent environment so it is
      // never written into this generated file. Set it once before `pm2 start`.
      [CLAUDE_TOKEN_ENV]: `process.env.${CLAUDE_TOKEN_ENV}`,
    },
  }));

  // Build the JS source by hand so the Claude token value is a live
  // `process.env.X` reference rather than a quoted string.
  const appBlocks = apps
    .map((app) => {
      const env = Object.entries(app.env)
        .map(([k, v]) =>
          k === CLAUDE_TOKEN_ENV ? `        ${k}: ${v},` : `        ${k}: ${JSON.stringify(v)},`
        )
        .join('\n');
      return `    {
      name: ${JSON.stringify(app.name)},
      script: ${JSON.stringify(app.script)},
      args: ${JSON.stringify(app.args)},
      interpreter: ${JSON.stringify(app.interpreter)},
      cwd: ${JSON.stringify(app.cwd)},
      autorestart: ${app.autorestart},
      max_restarts: ${app.max_restarts},
      watch: ${app.watch},
      max_memory_restart: ${JSON.stringify(app.max_memory_restart)},
      env: {
${env}
      },
    }`;
    })
    .join(',\n');

  return `// AUTO-GENERATED by deploy/gen-config.mjs from deploy/tenants.json — DO NOT EDIT.
// Regenerate with: node deploy/gen-config.mjs
module.exports = {
  apps: [
${appBlocks}
  ],
};
`;
}

function renderCaddyfile(cfg) {
  const blocks = cfg.tenants.map((t) => {
    const host = `${t.subdomain}.${cfg.domain}`;
    const upstream = `${cfg.bindHost ?? '127.0.0.1'}:${t.port}`;
    const user = t.authUser ?? t.id;
    return `${host} {
\t# Webhooks self-verify HMAC signatures — leave them un-gated so providers can reach them.
\t@webhooks path ${WEBHOOK_PATHS.join(' ')}
\thandle @webhooks {
\t\treverse_proxy ${upstream}
\t}

\t# Everything else requires a login (identity-based — survives IP changes).
\thandle {
\t\tbasic_auth {
\t\t\t${user} ${t.authHash}
\t\t}
\t\treverse_proxy ${upstream}
\t}
}`;
  });

  return `# AUTO-GENERATED by deploy/gen-config.mjs from deploy/tenants.json — DO NOT EDIT.
# Regenerate with: node deploy/gen-config.mjs
# Caddy auto-provisions Let's Encrypt TLS for each host below.

${blocks.join('\n\n')}
`;
}

function fail(msg) {
  console.error(`\x1b[31m✖ ${msg}\x1b[0m`);
  process.exit(1);
}
function warn(msg) {
  console.warn(`\x1b[33m⚠ ${msg}\x1b[0m`);
}
function ok(msg) {
  console.log(`\x1b[32m✓ ${msg}\x1b[0m`);
}

const cfg = loadConfig();
const ecosystemPath = join(here, 'ecosystem.config.cjs');
const caddyPath = join(here, 'Caddyfile');

writeFileSync(ecosystemPath, renderEcosystem(cfg));
writeFileSync(caddyPath, renderCaddyfile(cfg));

ok(`Wrote ${ecosystemPath}`);
ok(`Wrote ${caddyPath}`);
console.log(`\nTenants (${cfg.tenants.length}):`);
for (const t of cfg.tenants) {
  console.log(
    `  • ${t.id.padEnd(12)} https://${t.subdomain}.${cfg.domain}  →  127.0.0.1:${t.port}  (SHEP_HOME=${shepHome(cfg, t)})`
  );
}
console.log(`\nNext:`);
console.log(`  export ${CLAUDE_TOKEN_ENV}=...        # shared Claude key (once per shell/systemd)`);
console.log(`  pm2 start ${ecosystemPath} --update-env`);
console.log(`  sudo cp ${caddyPath} /etc/caddy/Caddyfile && sudo systemctl reload caddy`);
