/**
 * Compliance control seed data (feature 098, phase 9 / task-52).
 *
 * Two open-standard frameworks ship at MVP:
 *
 *   - OWASP ASVS L1/L2: a curated subset of OWASP ASVS v4.0.3 controls
 *     keyed by their canonical "V<chapter>.<section>.<requirement>"
 *     identifier. Used by the SARIF adapter when scanners reference ASVS
 *     taxa (Semgrep, CodeQL Security pack, etc.).
 *
 *   - CWE Top 25 (2023): the canonical CWE-* identifiers for the 25
 *     most-dangerous software weaknesses, used both by scanners that
 *     report a CWE directly and by the SARIF "CWE" taxonomy.
 *
 * Idempotence: every row carries a stable `id` (`cc-<framework>-<slug>`)
 * AND the migration writes through INSERT OR IGNORE against the partial
 * unique index `(framework_id, control_id)` — so a second migration run
 * (and tests that re-run migrations on a fresh in-memory DB) get exactly
 * the same set of rows.
 *
 * Adding a new framework (SOC 2, PCI DSS, HIPAA) means appending rows to
 * this constant — no schema change.
 */

import { ComplianceFramework } from '../../../../../domain/generated/output.js';

export interface ComplianceControlSeedRow {
  id: string;
  frameworkId: ComplianceFramework;
  controlId: string;
  title: string;
  description: string;
}

const OWASP_ASVS_L1_L2: ComplianceControlSeedRow[] = [
  {
    id: 'cc-asvs-v1-2-3',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V1.2.3',
    title: 'Authentication architecture is documented',
    description:
      'Verify that the application uses a single vetted authentication mechanism that is known to be secure, can be extended to include strong authentication, and has sufficient logging and monitoring to detect account abuse or breaches.',
  },
  {
    id: 'cc-asvs-v2-1-1',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V2.1.1',
    title: 'Passwords are at least 12 characters',
    description:
      'Verify that user-set passwords are at least 12 characters in length (after multiple spaces are combined).',
  },
  {
    id: 'cc-asvs-v2-1-7',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V2.1.7',
    title: 'Passwords checked against breach dataset',
    description:
      'Verify that passwords submitted during account registration, login, and password change are checked against a set of breached passwords.',
  },
  {
    id: 'cc-asvs-v3-2-1',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V3.2.1',
    title: 'Session tokens generated by approved cryptographic algorithm',
    description:
      'Verify the application generates a new session token on user authentication and that session tokens have at least 64 bits of entropy.',
  },
  {
    id: 'cc-asvs-v3-3-1',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V3.3.1',
    title: 'Logout terminates session',
    description:
      'Verify that logout and expiration invalidate the session token, such that the back button or a downstream relying party does not resume an authenticated session.',
  },
  {
    id: 'cc-asvs-v4-1-1',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V4.1.1',
    title: 'Access control enforced server-side',
    description:
      'Verify that the application enforces access control rules on a trusted service layer, especially if client-side access control is present and could be bypassed.',
  },
  {
    id: 'cc-asvs-v5-1-3',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V5.1.3',
    title: 'Input validation enforced on trusted service layer',
    description:
      'Verify that all input is validated using positive validation (allow lists) on a trusted service layer.',
  },
  {
    id: 'cc-asvs-v5-3-4',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V5.3.4',
    title: 'Parameterized queries used for data access',
    description:
      'Verify that data selection or database queries use parameterized queries, ORMs, entity frameworks, or are otherwise protected from SQL injection and other database injection attacks.',
  },
  {
    id: 'cc-asvs-v5-3-5',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V5.3.5',
    title: 'Output encoding context-appropriate',
    description:
      'Verify that where parameterized or safer mechanisms are not present, context-specific output encoding is used to protect against injection attacks (XSS, command injection, etc.).',
  },
  {
    id: 'cc-asvs-v6-2-1',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V6.2.1',
    title: 'Approved cryptographic algorithms in use',
    description:
      'Verify that all cryptographic modules fail securely and that errors are handled in a way that does not enable padding oracle attacks.',
  },
  {
    id: 'cc-asvs-v7-1-1',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V7.1.1',
    title: 'Logs do not contain sensitive data',
    description:
      'Verify that the application does not log credentials, payment details, or other sensitive data; session tokens should only be stored in logs in an irreversible, hashed form.',
  },
  {
    id: 'cc-asvs-v8-2-2',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V8.2.2',
    title: 'Anti-caching headers on sensitive data',
    description:
      'Verify that data stored in client side storage (such as HTML5 local storage, session storage, IndexedDB, regular cookies, or Flash cookies) does not contain sensitive data or PII.',
  },
  {
    id: 'cc-asvs-v9-1-1',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V9.1.1',
    title: 'TLS used for all client connectivity',
    description:
      'Verify that secured TLS is used for all client connectivity and does not fall back to insecure or unencrypted protocols.',
  },
  {
    id: 'cc-asvs-v10-3-2',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V10.3.2',
    title: 'Code integrity protections enforced',
    description:
      'Verify that the application employs integrity protections, such as code signing or sub-resource integrity, to prevent malicious code from being injected into deployed assets.',
  },
  {
    id: 'cc-asvs-v12-3-1',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V12.3.1',
    title: 'User-supplied filenames sanitised',
    description:
      'Verify that user-submitted filename metadata is not used directly by system or framework filesystem and that a URL API is used to protect against path traversal.',
  },
  {
    id: 'cc-asvs-v13-1-3',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V13.1.3',
    title: 'API URLs do not expose sensitive information',
    description:
      'Verify API URLs do not expose sensitive information, such as the API key, session tokens, etc.',
  },
  {
    id: 'cc-asvs-v14-2-1',
    frameworkId: ComplianceFramework.OwaspAsvs,
    controlId: 'V14.2.1',
    title: 'Third-party dependencies tracked and patched',
    description:
      'Verify that all components are up to date, preferably using a dependency checker during build or compile time.',
  },
];

const CWE_TOP_25_2023: ComplianceControlSeedRow[] = [
  {
    id: 'cc-cwe-787',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-787',
    title: 'Out-of-bounds Write',
    description:
      'The product writes data past the end, or before the beginning, of the intended buffer.',
  },
  {
    id: 'cc-cwe-79',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-79',
    title: "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')",
    description:
      'The product does not neutralize or incorrectly neutralizes user-controllable input before it is placed in output used as a web page that is served to other users.',
  },
  {
    id: 'cc-cwe-89',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-89',
    title: "Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')",
    description:
      'The product constructs all or part of an SQL command using externally-influenced input without neutralizing special elements that could modify the intended SQL command.',
  },
  {
    id: 'cc-cwe-416',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-416',
    title: 'Use After Free',
    description:
      'Referencing memory after it has been freed can cause a program to crash, use unexpected values, or execute code.',
  },
  {
    id: 'cc-cwe-78',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-78',
    title:
      "Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')",
    description:
      'The product constructs all or part of an OS command using externally-influenced input but does not neutralize special elements that could modify the intended command.',
  },
  {
    id: 'cc-cwe-20',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-20',
    title: 'Improper Input Validation',
    description:
      'The product receives input or data but does not validate or incorrectly validates that the input has the properties required to process the data safely.',
  },
  {
    id: 'cc-cwe-125',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-125',
    title: 'Out-of-bounds Read',
    description:
      'The product reads data past the end, or before the beginning, of the intended buffer.',
  },
  {
    id: 'cc-cwe-22',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-22',
    title: "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')",
    description:
      'The product uses external input to construct a pathname that resolves to a location outside of a restricted directory.',
  },
  {
    id: 'cc-cwe-352',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-352',
    title: 'Cross-Site Request Forgery (CSRF)',
    description:
      'The web application does not, or cannot, sufficiently verify whether a well-formed, valid, consistent request was intentionally provided by the user.',
  },
  {
    id: 'cc-cwe-434',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-434',
    title: 'Unrestricted Upload of File with Dangerous Type',
    description:
      'The product allows the upload or transfer of dangerous file types that are automatically processed within the product environment.',
  },
  {
    id: 'cc-cwe-862',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-862',
    title: 'Missing Authorization',
    description:
      'The product does not perform an authorization check when an actor attempts to access a resource or perform an action.',
  },
  {
    id: 'cc-cwe-476',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-476',
    title: 'NULL Pointer Dereference',
    description:
      'A NULL pointer dereference occurs when the application dereferences a pointer that it expects to be valid, but is NULL, typically causing a crash or exit.',
  },
  {
    id: 'cc-cwe-287',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-287',
    title: 'Improper Authentication',
    description:
      'When an actor claims to have a given identity, the product does not prove or insufficiently proves that the claim is correct.',
  },
  {
    id: 'cc-cwe-190',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-190',
    title: 'Integer Overflow or Wraparound',
    description:
      'The product performs a calculation that can produce an integer overflow or wraparound when the logic assumes that the resulting value will always be larger than the original value.',
  },
  {
    id: 'cc-cwe-502',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-502',
    title: 'Deserialization of Untrusted Data',
    description:
      'The product deserializes untrusted data without sufficiently verifying that the resulting data will be valid.',
  },
  {
    id: 'cc-cwe-77',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-77',
    title: "Improper Neutralization of Special Elements used in a Command ('Command Injection')",
    description:
      'The product constructs all or part of a command using externally-influenced input.',
  },
  {
    id: 'cc-cwe-119',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-119',
    title: 'Improper Restriction of Operations within the Bounds of a Memory Buffer',
    description:
      'The product performs operations on a memory buffer, but can read from or write to a memory location that is outside of the intended boundary.',
  },
  {
    id: 'cc-cwe-798',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-798',
    title: 'Use of Hard-coded Credentials',
    description:
      'The product contains hard-coded credentials, such as a password or cryptographic key, which it uses for its own inbound authentication, outbound communication to external components, or encryption of internal data.',
  },
  {
    id: 'cc-cwe-918',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-918',
    title: 'Server-Side Request Forgery (SSRF)',
    description:
      'The web server receives a URL or similar request from an upstream component and retrieves the contents of this URL without sufficiently ensuring that the request is being sent to the expected destination.',
  },
  {
    id: 'cc-cwe-306',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-306',
    title: 'Missing Authentication for Critical Function',
    description:
      'The product does not perform any authentication for functionality that requires a provable user identity or consumes a significant amount of resources.',
  },
  {
    id: 'cc-cwe-362',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-362',
    title:
      "Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition')",
    description:
      'The product contains a code sequence that can run concurrently with other code, and the code sequence requires temporary, exclusive access to a shared resource, but a timing window exists in which the shared resource can be modified by another code sequence operating concurrently.',
  },
  {
    id: 'cc-cwe-269',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-269',
    title: 'Improper Privilege Management',
    description:
      'The product does not properly assign, modify, track, or check privileges for an actor, creating an unintended sphere of control for that actor.',
  },
  {
    id: 'cc-cwe-94',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-94',
    title: "Improper Control of Generation of Code ('Code Injection')",
    description:
      'The product constructs all or part of a code segment using externally-influenced input from an upstream component, but it does not neutralize or incorrectly neutralizes special elements that could modify the syntax or behavior of the intended code segment.',
  },
  {
    id: 'cc-cwe-863',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-863',
    title: 'Incorrect Authorization',
    description:
      'The product performs an authorization check when an actor attempts to access a resource or perform an action, but it does not correctly perform the check.',
  },
  {
    id: 'cc-cwe-276',
    frameworkId: ComplianceFramework.CweTop25,
    controlId: 'CWE-276',
    title: 'Incorrect Default Permissions',
    description:
      'During installation, installed file permissions are set to allow anyone to modify those files.',
  },
];

export const COMPLIANCE_CONTROL_SEED_ROWS: readonly ComplianceControlSeedRow[] = [
  ...OWASP_ASVS_L1_L2,
  ...CWE_TOP_25_2023,
];

export const OWASP_ASVS_SEED_COUNT = OWASP_ASVS_L1_L2.length;
export const CWE_TOP_25_SEED_COUNT = CWE_TOP_25_2023.length;
